class TryCatchDemo {
    public static void main(String[] args) {
        //q20 sc = new q20(System.in);
        //int a = sc.nextInt(), b = sc.nextInt();
        try {
           // System.out.println("Result: " + (  ));
        } catch (ArithmeticException e) {
            System.out.println("Cannot divide by zero");
        }
    }
}